### ISSUE TITLE
README.md Error

### ISSUE THREAD

**Issue by Corrupter-rot** [syash7202/Tic-Tac-Toe#1]
```
git clone  https://github.com/syash7202/Tic-Tak-Toe.git  $HOME/Tic-Tak-Toe
cd $HOME/Tic-Tak-Toe
cdmod 777 tic-tak-toe
./tic-tak-toe
```

3rd Line should be `chmod 777 tic-tak-toe`

Please correct it

**Comment by niksingh710** [comment]
No in my opinion it should be more precise 
`chmod +x tic-tak-toe`
and as u can see [reference](https://docs.nersc.gov/filesystems/unix-file-permissions/)

**Comment by Corrupter-rot** [comment]
Bawli gand
